### ISSUE TITLE
CSS - overflow property

### ISSUE THREAD

**Issue by thierryteyssier** [matjaztrontelj/PinegrowCommunity#10]
Hi,

I do not find overflow property and box-shadow property in the CSS panel,  is it an oversight or a next feature?

And you have a bug with the vars panel, my var name is in lower case but it appears in uppercase in the panel (see attached)

Many thanks

Thierry
![vars](https://f.cloud.github.com/assets/2173841/2117063/6268ba52-90b2-11e3-8046-172e1881705d.png)

**Comment by matjaztrontelj** [comment]
Thanks Thierry! Overflow is fixed, for shadows use code edit on </> the CSS rule. It would be nice to have a control for it eventually.

Var names are also fixed.
