### ISSUE TITLE
Improve design

### ISSUE THREAD

**Issue by thierryteyssier** [matjaztrontelj/PinegrowCommunity#13]
Hi Pinegrow Team,

Is it in your plan to improve the design of your app? I like your app and I use it everyday but it will be great if the look and fill will be closest of Adobe Reflow or Macaw.

Thanks

**Comment by matjaztrontelj** [comment]
Thanks Thierry!

Yes, we have a redesign coming up. UI definetely needs an improvmenent.

**Comment by Romainpetit** [comment]
As the interface is web based, it would be also great to have the possibility to override the panel design by using our own css.

**Comment by matjaztrontelj** [comment]
Good idea, Romain!

On Thu, Apr 10, 2014 at 11:20 PM, Romain PETIT notifications@github.comwrote:

> As the interface is web based, it would be also great to have the
> possibility to override the panel design by using our own css.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/matjaztrontelj/PinegrowCommunity/issues/13#issuecomment-40106234
> .

## 

Humane tehnologije d.o.o.
Knezov štradon 14 B
1000 Ljubljana
T: 031 380 466
www.humane-tehnologije.si
