### ISSUE TITLE
Any plans to support dual screens

### ISSUE THREAD

**Issue by clarkedesign** [matjaztrontelj/PinegrowCommunity#19]
hi,

Wondering if there are any plans to support Dual Screen Development ?

Be great to have to ability to span two screens with lots of multiple sizes for some serious development.

**Comment by niutech** [comment]
+1 for this!

**Comment by ialex** [comment]
+1

**Comment by yustasmaddy** [comment]
I sharply encourage that idea - it'll be very useful!!!
