### ISSUE TITLE
Feature request: Custom tabs/spaces

### ISSUE THREAD

**Issue by jcamachott** [matjaztrontelj/PinegrowCommunity#57]
It changes the tabs in my html code to 4 spaces (I originally had 2). Please include an option to use two spaces.

Thanks

**Comment by matjaztrontelj** [comment]
It's on the todo list.

Matjaz

On Wed, Jun 18, 2014 at 4:45 AM, John Camacho notifications@github.com
wrote:

> It changes the tabs in my html code to 4 spaces (I originally had 2).
> Please include an option to use two spaces.
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matjaztrontelj/PinegrowCommunity/issues/57.

## 

_Matjaz Trontelj_
Co-founder of Pinegrow http://pinegrow.com/, Booklers
http://getbooklers.com and pllop.it

Our new product Pinegrow is out. Kindly take a look: www.pinegrow.com
Please check out our new apps Life is Beautiful
https://itunes.apple.com/us/app/life-is-beautiful-create-posters/id607999197?mt=8
, Bible Surprise
https://itunes.apple.com/us/app/bible-surprise-your-photos/id643673873?mt=8,
Pope Francis
https://itunes.apple.com/us/app/pope-francis-daily-surprise/id685158626?mt=8
, Zen Habits https://itunes.apple.com/th/app/id681123869?mt=8

**Comment by jcamachott** [comment]
Thanks for the addition to 1.15. Greatly appreciated.
