### ISSUE TITLE
Outline Block Element - a good idea for pinegrow

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [matjaztrontelj/PinegrowCommunity#78]
I saw this feature in FireFox extencion*\* "Web developer toolbar".**

This feature (see the JPEG i added) - is really good for better **understand the layout of your html**. And Its really handy to outline your block if you want.

![git-hub](https://cloud.githubusercontent.com/assets/16711871/12901518/dd3c0534-cec4-11e5-8d1a-0bf70078d328.jpg)

**Comment by badcat** [comment]
Pinegrow already shows all individual elements when you hover over each - however you could just add something like this:

```
* {border: 1px solid red;}
```

temporarily into your css or page and see what's going on with Everything (divs, spans - all of it), no?

**Comment by Ezra-Siton-UIX** [comment]
I know i can do this - but Auto mode is mabye better (With 3-4 colors - Nav in green outline - 
Text in red - Blocks structure - in blue and so on)

Like in photoshop - You have "clean" mode - and mode with guidelines and all of the Extras - and you Click Ctr+H to switch modes.
