### ISSUE TITLE
Unfold // Fold the Tree View

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [matjaztrontelj/PinegrowCommunity#79]
In pingerow sometime you dont want by hand close all the tags in the Tree.

It would be helpful to have something like the Conseopt of NodePad++ (you can Unfold // Fold the tree code) - when you want "Smaller" tree of if you want to work on specific section of the Tree. 

By deafult is will stay "Unfold".

![git-hub-2](https://cloud.githubusercontent.com/assets/16711871/12901998/27def5ae-cec7-11e5-973e-770fd5855d16.jpg)

**Comment by badcat** [comment]
Pinegrow will keep open/closed item states in the **Tree** once set up - even after closing the document. However, I too, would like to see the **Lib** hold open/closed states.

**Comment by Ezra-Siton-UIX** [comment]
I dont know if this Is related to this issue. Anyway in pinegrow Release 2.7 :) this Fold feature added. THANKS! :+1: :)
