### ISSUE TITLE
UI pattern for select units

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [matjaztrontelj/PinegrowCommunity#82]
This pattern use by great software's like Adobe Photoshop // Windows Word (very good and recolonize). 
I think it could be great to use this pattern for units in pinegrow css menu.
In word for example 100% of the time i dont write by hand the size of the font and use this pattern.

![select-units-pattern](https://cloud.githubusercontent.com/assets/16711871/13565608/ccb95b12-e459-11e5-9553-a0c66a617b8b.jpg)

**The pattern - the label have -"2 option areas"-**
1. Type area (left area)
2. by drop down area (right arrow) 
## The advantage
1. The software give you "popular" units - in font for example 12px-20px // in margin/padding 10,15,20, 25, 30,40, 50, 100, 150, 200 and so on... (small units and some big units)
2. You dont change the state of the software (The behavior of current version) - only add great functionality. The user still can type anything he want (1em, 100%, medium or use less/sass var)

3.*\* In photoshop you also can drag (right-left) to increase-decrease units - really useful (for the future).

**Comment by matjaztrontelj** [comment]
Thanks! We plan to do that and also include values used in current project
in the dropdown / auto-complete list.

Matjaz

On Mon, Mar 7, 2016 at 10:46 AM, Siton-Design notifications@github.com
wrote:

> This pattern use by great software's like Adobe Photoshop // Windows Word
> (very good and recolonize). I think it could be great to use this pattern
> for units in pinegrow css menu.
> 
> [image: select-units-pattern]
> https://cloud.githubusercontent.com/assets/16711871/13565608/ccb95b12-e459-11e5-9553-a0c66a617b8b.jpg
> 
> _The pattern - the label have -"2 areas"-_
> 1. Type area (left area)
> 2. by drop down area (right arrow)
> The advantage
> 1. The software give you "popular" units - in font for example
>    12px-20px // in margin/padding 10,15,20, 25, 30,40, 50, 100, 150, 200 and
>    so on... (small units and some big units)
> 2. You dont change the state of the software (The behavior of current
>    version) - only add great functionality. The user still can type anything
>    he want (1em, 400px, 100%, medium)
> 
> 3.*\* In photoshop you also can drag (right-left) to increase-decrease
> units - really useful (for the future).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matjaztrontelj/PinegrowCommunity/issues/82.

## 

_Matjaz Trontelj_
Author of Pinegrow Web Editor http://pinegrow.com/

**Comment by Ezra-Siton-UIX** [comment]
Thanks a lot :) :) :+1:
