### ISSUE TITLE
Version 2.93 - PRO - Svg make the system to "freeze"

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [matjaztrontelj/PinegrowCommunity#84]
If i use the code editor and put only this code

```
<svg>
some svg values....
</svg>
```

I can go out of the code + cancel dont work + esc.

The solution is to add some wrapper (or select the parent div).

```
<div>
<svg>
some values....
</svg>
</div>
```

Make live test to see this issue.

**Comment by matjaztrontelj** [comment]
Fixed. Will be out in 2.94. Thanks!

**Comment by Ezra-Siton-UIX** [comment]
Thanks!!!!!!!!!! :) Great
